#version controlled .bashrc from github




# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

PS1='\n\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[0;33m\]\w\n\[\e[0m\]$(__git_ps1 " (%s)")\$ '


# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.config/bash/bash_aliases ]; then
    . ~/.config/bash/bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
source /usr/share/git/completion/git-completion.bash

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#Enable find-the-command
#You can also append 'su' option to use su instead of sudo
#for root access, 'noprompt' to disable installation
#prompt at all, or 'quiet' to decrease verbosity, e.g.:
#source /usr/share/doc/find-the-command/ftc.zsh noprompt quiet

source /usr/share/doc/find-the-command/ftc.bash

#Git prompt
source /usr/share/git/completion/git-prompt.sh
set GIT_PS1_SHOWUPSTREAM
set GIT_PS1_SHOWUNTRACKEDFILES
set GIT_PS1_SHOWSTASHSTATE
set GIT_PS1_SHOWDIRTYSTATE


#Keychain

eval $(keychain --eval --agents ssh --nogui --noask --timeout 60 --quiet id_ed25519_myt430)
