#!/bin/bash
alias vim='nvim'
alias c='clear'
alias myip="curl http://ipecho.net/plain; echo"
alias ip="ip -color=auto"
alias dmesgl="dmesg --color=always | less"
alias cfg='cd ~/.config'

#cd shortcuts
alias ..='cdl ..'
alias cd..='cdl ..'
alias ...='cdl ../..'
alias ....='cdl ../../..'

#alias ssh='TERM=xterm-256color ssh'

#ls shortcuts and always colored
alias ls='ls --color=auto'
alias ll='ls -lFh --color=auto'
alias lla='ls -AlFh --color=auto'
alias la='ls -AF --color=auto'
alias l='ls -CF --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#git shortcuts
alias gsu='echo "Updating Submodules from Remote"; git submodule update --remote
&& echo "Committing Changes to this Repo"; git commit -a -m "update submodules"
&& echo "Pushing Commit to Remote"; git push origin main'
alias gcm='git commit -a -m'
alias gs='git status'

#clamscan is recursive with a timestamped log
alias clamscan='sudo freshclam && clamscan -r -o -l ~/clamscan_$(date +"%F_%H:%M").log'

#Pacman
alias autoremove='pacman -Qtdq | pacman -Rns -'
