#!/bin/bash
alias vim='nvim'
alias c='clear'
alias myip="curl http://ipecho.net/plain; echo"
alias ip="ip -color=auto"
alias dmesgl="dmesg --color=always | less"

#cd shortcuts
alias ..='cd ..'
alias cd..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias ssh='TERM=xterm-256color ssh'

#ls shortcuts and always colored
alias ls='ls --color=auto'
alias ll='ls -AlFh --color=auto'
alias la='ls -AF --color=auto'
alias l='ls -CF --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#git shortcuts
alias gsu='git submodule update --remote && git commit -a -m "update submodule" && git push origin main'

#clamscan is recursive with a timestamped log
alias clamscan='sudo freshclam && clamscan -r -o -l ~/clamscan_$(date +"%F_%H:%M").log'

